- hosts: localhost
  connection: local
  tasks:
    - name: Create development VM
      community.general.lxd_container:
        name: development
        url: unix:/run/lxd.socket
        type: virtual-machine
        state: started
        config: 
          user.user-data: |
            #cloud-config
            users:
              - default
              - name: jonas
                sudo: ALL=(ALL) NOPASSWD:ALL
                ssh_authorized_keys:
                  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAWG0a7lPXYBqF5V5exQGmpLVpYi0Bed3MvYxNEobsR2 jonas.govaerts1@telenetgroup.be
                shell: /bin/bash
            write_files:
              - path: /etc/ssh/sshd_config
                content: |
                     Port 22
                     Protocol 2
                     HostKey /etc/ssh/ssh_host_rsa_key
                     HostKey /etc/ssh/ssh_host_dsa_key
                     HostKey /etc/ssh/ssh_host_ecdsa_key
                     HostKey /etc/ssh/ssh_host_ed25519_key
                     UsePrivilegeSeparation yes
                     KeyRegenerationInterval 3600
                     ServerKeyBits 1024
                     SyslogFacility AUTH
                     LogLevel INFO
                     LoginGraceTime 120
                     PermitRootLogin no
                     StrictModes yes
                     RSAAuthentication yes
                     PubkeyAuthentication yes
                     IgnoreRhosts yes
                     RhostsRSAAuthentication no
                     HostbasedAuthentication no
                     PermitEmptyPasswords no
                     ChallengeResponseAuthentication no
                     X11Forwarding yes
                     X11DisplayOffset 10
                     PrintMotd no
                     PrintLastLog yes
                     TCPKeepAlive yes
                     AcceptEnv LANG LC_*
                     Subsystem sftp /usr/lib/openssh/sftp-server
                     UsePAM yes
                     AllowUsers jonas
            runcmd:
              - service enable ssh
              - service start ssh
          security.secureboot: "false"
        ignore_volatile_options: true
        wait_for_ipv4_addresses: true
        profiles: ["default"]
        source:
          protocol: simplestreams
          type: image
          mode: pull
          server: https://cloud-images.ubuntu.com/releases/
          alias: "20.04"
        timeout: 600
      register: development

    - name: Output ip addresses
      debug:
        var: development.addresses

- hosts:
    - development
  tasks:
    - name: apt install packages
      apt:
        update_cache: "yes"
        pkg:
          - git
          - python3.8
          - python3-pip
    - name: install pipenv
      pip:
        name:
          - pipenv
